### Create room
POST http://localhost:8080/chat/api/rooms
Content-Type: application/json
Accept: application/xml

{
  "name": "room3",
  "members": ["John","Ann","Mark"]
}

###
POST http://localhost:8080/chat/api/messages/send
Content-Type: application/json
Accept: application/xml

{
  "content": "Works",
  "senderName": "John",
  "roomName": "room1"
}

###
GET http://localhost:8080/chat/api/messages/history/room2?memberName=John


### Get File
GET http://localhost:8080/chat/api/files/room1/1