version: '3'
services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - "9001:5432"
    environment:
      - POSTGRES_DB=training
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data
    command: [ "postgres", "-c", "log_statement=all" ]
    # volumes:
    #  - ./data:/data
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports:
        # AMQP protocol port
        - '5670:5670'
        # HTTP management UI
        - '15670:15670'

