version: '3'
services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - "9001:5432"
    environment:
      - POSTGRES_DB=training
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data
    command: [ "postgres", "-c", "log_statement=all" ]
  rabbitmq3:
    container_name: "some-rabbit"
    hostname: "my-rabbit"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '15672:15672'
      - '5672:5672'