version: '3'
services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - "9001:5432"
    environment:
      - POSTGRES_DB=training
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data
    command: ["postgres", "-c", "log_statement=all"]
    # volumes:
    #  - ./data:/data
